### ISSUE TITLE
[CLOUD] 클라우드 환경 테스트

### ISSUE THREAD

**Issue by ghk01214** [KTB-Sixmen/gitfolio_cloud#15]
### Description
각 파트별 개발 결과물을 클라우드 환경에서 테스트

### TODO

- [x] 프론트엔드 작동 확인
- [x] 백엔드 작동 확인
- [x] AI 작동 확인

### ETC (관련 자료 및 링크, 사진 등)
